### ISSUE TITLE
x20源代码问题

### ISSUE THREAD

**Issue by fhh200000** [EsonTang/programmer#1]
开发者你好：
我是x20的用户，现在想要为x20移植一份Recovery, 这需要x20的内核源代码。
请问您能方便分享一份吗？谢谢！
（由于移植Recovery的原因，应该只需要开源的kernel部分就可以了）

**Comment by EsonTang** [comment]
出多少钱

**Comment by fhh200000** [comment]
> 出多少钱

您觉得大概多少合适呢？

**Comment by EsonTang** [comment]
还是你说多少钱吧，你要android 几点几的啊

**Comment by fhh200000** [comment]
> 还是你说多少钱吧，你要android 几点几的啊

hmmm我现在还是学生，所以不太了解价格行情。
价格的话，我目前的心理价位是kernel代码100左右(编译出内核就行)，如果是完整源代码的话，大概200这样吧。
因为昂达x20严格意义上已经算半个过时产品了，加上囊中羞涩，估计只能出这么多了。
系统版本的话，昂达官方给出的版本是安卓7.1的，所以7.1就可以了。不过如果有8.0的话，那就再好不过了。
如果您觉得价格太低的话，就只能算啦。

**Comment by fhh200000** [comment]
那我先关闭Issue了。
如果您还想联系我议价或其他事项，可以发邮件到fhh@fhh200000.com。
谢谢您！
